<?php

/**
* @file
* A block displaying a lead generation form
* Implements hook_permission
*/

function lead_generation_permission() {
  return array(
    'submit lead_generation' => array(
      'title' => t('Submit lead_generation'),
      'description' => t('Submit lead generation.'),
    ),
  );
}

/**
* Implements hook_menu
*/

function lead_generation_menu() {
  $items['vote-now'] = array(
    'title' => 'Lead Generation Form',
    'type' => MENU_NORMAL_ITEM,
    'description' => 'A form to generate leads for a candidate.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('lead_generation_form'),
    'access callback' => TRUE,
  );
  return $items;
}



/**
*  Generated page displaying a lead generation form
* Implements hook_page
*/

function lead_generation_page() {
  return drupal_get_form('lead_generation_form');
}


/**
* Block information to be displayed in the blocks list
* Implements hook_block_info
*/

function lead_generation_block_info() {
  $blocks = array();
  $blocks['lead_generation_block'] = array(
    'info' =>t('Lead Generation Block'),
  );
  return $blocks; 
}


/**
* The block view that pulls in the lead generation form
* Implements hook_block_view
*/

function lead_generation_block_view($delta = '') {
  $block = array();
  switch($delta) {
    case 'lead_generation_block' :
      $block['subject'] = t('Vote now');
      $block['content'] = drupal_get_form('lead_generation_form');
      break;
  }

  return $block;
}


// /**
// * Save block configuration
// */
// function lead_generation_block_save($delta = '', $edit = array()) {
//   switch($delta) {
//     case 'my_block' :
//     // variable_set('text_variable', $edit['text_body']['value']);

//     //saving the file and setting it to a permanent state
//     // $file = file_load($edit['file']);
//     // $file->status = FILE_STATUS_PERMANENT;
//     // file_save($file);
//     $block = block_load('lead_generation', $delta);
//     file_usage_add($file, 'lead_generation', 'block', $block->bid);
    
//     break;
//   }
// }


/**
* Implements hook_form
*/

function lead_generation_form($form, &$form_state) {
  $form['name'] = array(
    '#title' => t('Name'),
    '#type' => 'textfield',
    '#required' => TRUE,
    '#description' => t('Type in your name.'),
  );
  $form['email'] = array(
    '#title' => t('Email address'),
    '#type' => 'textfield',
    '#required' => TRUE,
    '#description' => t('Type in your email address.'),
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Submit',
  );
  return $form;
}

// function lead_generation_form_validate($form, &$form_state) {
//   // print('<pre>'.print_r($form_state['values'],string).'</pre>');die();
//   if (!is_string($form_state['string']['name'])) {
//     form_set_error('name', t('You must enter a valid number'));
//     return FALSE;
//   }
//   return TRUE;
// }

/**
* Submit handler for the lead_generation_form. Inserts entry into database.
* Implements hook_form_submit
*/

function lead_generation_form_submit($form, &$form_state) {
  $lg_id = db_insert('lead_generation')
  ->fields(array(
      'name' => $form_state['values']['name'],
      'email' => $form_state['values']['email'],
  ))
  ->execute();

  drupal_set_messange(t('Your vote has been submitted!'));
}
