<?php

/**
* @file
* A block displaying a lead generation form
*/

function lead_generation_menu() {
  $items['vote-now'] = array(
    'title' => 'Lead Generation Form',
    'description' => 'A form to generate leads for a candidate.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('lead_generation_form'),
    'access callback' => TRUE,
  );
  return $items;
}



/**
*  Generated page displaying a lead generation form
*/

function lead_generation_page() {
  return drupal_get_form('lead_generation_form');
}


/**
* Block information to be displayed in the blocks list
*/

function lead_generation_block_info() {
  $blocks = array();
  $blocks['lead_generation_block'] = array(
    'info' =>t('Lead Generation Block EEEEEEEEE'),
  );
  return $blocks; 
}


/**
* The block view that pulls in the lead generation form
*/

function lead_generation_block_view($delta = '') {
  $block = array();
  switch($delta) {
    case 'lead_generation_form' :
    $block['subject'] = t('Vote now');

    $block['content'] = drupal_get_form('lead_generation_form');
    break;
  }

  return $block;
}



/**
* Lead generation form
*/

function lead_generation_form($form, &$form_state) {
  $form['name'] = array(
    '#title' => t('Name'),
    '#type' => 'textfield',
    '#required' => TRUE,
    '#description' => t('Type in your name'),
  );
  $form['email'] = array(
    '#title' => t('Email address'),
    '#type' => 'textfield',
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Submit',
  );
  return $form;
}
